<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIi6ShMy\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIi6ShMy/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIi6ShMy.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIi6ShMy\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIi6ShMy\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ii6ShMy',
    'container.build_id' => '457ef80c',
    'container.build_time' => 1573666515,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIi6ShMy');
